/**
 * Embed the theme assets (background JPEG) as base64 data URIs into
 * src/client/assets.generated.ts, which theme.css.ts imports so the plugin
 * bundle stays a single offline file.
 * Run: node scripts/embed-assets.mjs  (then rebuild)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const b64 = f => readFileSync(join(root, 'assets', f)).toString('base64')

const bg = b64('bg-gandalf.jpg')

const out = `/**
 * GENERATED by scripts/embed-assets.mjs — do not edit by hand.
 * Source files: assets/ (background JPEG — free-license; Cinzel removed).
 */
export const BG_IMAGE = 'data:image/jpeg;base64,${bg}'
`
writeFileSync(join(root, 'src', 'client', 'assets.generated.ts'), out)
const kb = x => (x / 1024).toFixed(0) + 'KB'
console.log(`embedded: bg ${kb(bg.length)} base64`)
